# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SparseRowVar2 <- function(mat, mu, display_progress) {
    .Call(`_AssessME_SparseRowVar2`, mat, mu, display_progress)
}

SparseRowVarStd <- function(mat, mu, sd, vmax, display_progress) {
    .Call(`_AssessME_SparseRowVarStd`, mat, mu, sd, vmax, display_progress)
}

